spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/layim
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: true
debug: false
